### PR TITLE
Updated Cereal to v1.1.

### PR DESCRIPTION
**Pull request by dkorolev**
HT to @mzhurovich for revealing MacOS issues with Cereal.

@deathbaba : **IMPORTANT**, please upgrage.

Reviewing is probably best on per-commit level.

Thanks,
Dima

### CODE REVIEW

**Comment by dkorolev** [comment]
I should mention that all tests pass in `Bricks`, `Sherlock` and `AgreeDisagreeDemo`.

Thanks,
Dima

**Comment by dkorolev** [comment]
@deathbaba : Relevant links from @mzhurovich:

* https://github.com/USCiLab/cereal/issues/94
* https://github.com/USCiLab/cereal/issues/81

Thanks,
Dima

**Comment by mzhurovich** [comment]
@dkorolev :+1:

**Comment by sompylasar** [comment]
@dkorolev The readme and the patch LGTM. Nothing to say about the Cereal upgrade.

**Pull request merged**
