### PR TITLE
Allowed to concurrently run "/" and "/meta".

### PR DESCRIPTION
**Pull request by dkorolev**
Previously one open connection to "/" would block any other connections.

### CODE REVIEW

**Comment by dkorolev** [comment]
@deathbaba, @sompylasar : Please review after https://github.com/KnowSheet/Bricks/pull/46 and https://github.com/KnowSheet/Bricks/pull/47. Thanks!

**Comment by dkorolev** [comment]
@deathbaba @sompylasar Status check?

**Comment by sompylasar** [comment]
Multithreading LGTM, too.

**Comment by dkorolev** [comment]
Pushed the merge resolve conflict.

@deathbaba : Please do take a look at this PR, as well as https://github.com/KnowSheet/Bricks/pull/47 and https://github.com/KnowSheet/Bricks/pull/46.

Thanks!
Dima

**Pull request merged**
