### PR TITLE
Tests passing on Windows, part 2/2, Visual Studio files.

### PR DESCRIPTION
**Pull request by dkorolev**
This pull request wil be much easier to go through once https://github.com/KnowSheet/Bricks/pull/94 is merged.

Right now it's a mix of Visual Studio changes and source code changes. Which is not cool.

Thanks,
Dima

### CODE REVIEW

**Comment by deathbaba** [comment]
Have you checked tests and compilation on Win32 or Win64 or both? Should be both.

**Comment by dkorolev** [comment]
Yep, both Win32 and x64, both Debug and Release.

On Wednesday, February 25, 2015, Alex Zolotarev <notifications@github.com>
wrote:

> Have you checked tests and compilation on Win32 or Win64 or both? Should
> be both.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KnowSheet/Bricks/pull/95#issuecomment-76149331>.
>


-- 
Thanks,
Dima

http://dimakorolev.com/ | http://www.linkedin.com/in/dimakorolev |
dmitry.korolev@gmail.com | +1 (312) 593 2783

**Comment by dkorolev** [comment]
This pull request is almost exclusively Visual Studio project changes now. I'm merging it.

@deathbaba : Would appreciate it if you could skim through as a post-review.
@sompylasar : No action required :+1: 

Thanks,
Dima

**Comment by deathbaba** [comment]
LTGM

**Pull request merged**
