### PR TITLE
Test fixes.

### PR DESCRIPTION
**Pull request by dkorolev**

### CODE REVIEW

**Comment by dkorolev** [comment]
Ref.  https://github.com/KnowSheet/Bricks/issues/57

**Comment by sompylasar** [comment]
Thanks,looks good.

**Comment by sompylasar** [comment]
Btw, maybe test at least two headers so that the loop is tested, too?

**Comment by dkorolev** [comment]
Added a test with two headers. Didn't have cycles for anything else today except this change and https://github.com/KnowSheet/Bricks/pull/59. :(

@sompylasar : Please click "Merge" if this one looks good. Alex @deathbaba prefers it this way ("don't merge your own code"), and we're somewhat following this practice so far. Thanks!

**Pull request merged**
