### PR TITLE
One-line JSON serialization.

### PR DESCRIPTION
**Pull request by dkorolev**

### CODE REVIEW

**Comment by dkorolev** [comment]
CC @sompylasar.

**Comment by dkorolev** [comment]
@deathbaba Status check?

**Comment by sompylasar** [comment]
@dkorolev LGTM.

Please also add a test case with renaming "value0" to be more meaningful. It would serve as an example of how to do this.

**Comment by dkorolev** [comment]
@sompylasar : Will add a non-```value0``` test. Let me do it after everything is merged, handling three changes at once is a bit of a mess.

@deathbaba : Final review and merge?

Thanks,
Dima

**Pull request merged**
