### PR TITLE
Minor warnings cleanup on Apple.

### PR DESCRIPTION
**Pull request by dkorolev**

### CODE REVIEW

**Comment by dkorolev** [comment]
@mzhurovich / @deathbaba / @sompylasar : PTAL.

**Comment by sompylasar** [comment]
LGTM. Merge?

**Comment by dkorolev** [comment]
Let's merge the other one first. Just added a back tick there :)

**Comment by dkorolev** [comment]
Let's merge this one after https://github.com/KnowSheet/Bricks/pull/108.

**Comment by dkorolev** [comment]
Actually, I just checked: https://github.com/KnowSheet/Bricks/pull/108 contains all the changed introduced in this pull request.

(So much for me trying to get two small changes reviewed faster last night :) )

Thus, let me abandon this PR. Go https://github.com/KnowSheet/Bricks/pull/108.

**Pull request closed without merging**
