### PR TITLE
Extension for `WaitableAtomic` and the right `make_unique`.

### PR DESCRIPTION
**Pull request by dkorolev**

### CODE REVIEW

**Comment by dkorolev** [comment]
@mzhurovich PTAL

**Comment by dkorolev** [comment]
And one more piece: Variadic RTTI and `is_unique_ptr<>`.

@mzhurovich, PTAL. Thanks!

Dima

**Comment by mzhurovich** [comment]
@dkorolev LGTM!
Minor suggestion for naming - `BASE&& ptr` is not a pointer and this became looking more confusing with your new addition of `is_unique_ptr`. Maybe `BASE&& ref` ?

**Comment by dkorolev** [comment]
@mzhurovich : Thanks, PTAL!

**Comment by mzhurovich** [comment]
@dkorolev :+1: Merging!

**Pull request merged**
