### PR TITLE
strings::{Trim,ToLower,ToUpper}().

### PR DESCRIPTION
**Pull request by msft-dkorolev**

### CODE REVIEW

**Comment by msft-dkorolev** [comment]
@deathbaba @sompylasar @mzhurovich : PTAL.

(I can't assign either of you from this `msft-dkorolev` account, unfortunately. Ready to merge from my side -- @dkorolev.)

**Comment by msft-dkorolev** [comment]
PS: Isn't it cute how our issue numbers almost match pull requests?

In Google we had a joke that the number of interviews one conducts tends to equal to the number of MapReduce jobs one has written :)

Thanks,
Dima

**Comment by dkorolev** [comment]
@deathbaba : PTAL at some point later. Merging :-)

**Comment by deathbaba** [comment]
LGTM

**Pull request merged**
